### ISSUE TITLE
Option to splat points with transparency

### ISSUE THREAD

**Issue by Meekohi** [e-n-f/datamaps#13]
I've been trying to approximately reproduce a vector-based map I created. In the original, I splat dots at 40% opacity, and with color based on a timestamp:

![screenshot 2014-06-30 10 35 08](https://cloud.githubusercontent.com/assets/10985/3435903/6afc0ff4-009a-11e4-84c4-0e2880dcae9c.png)

Alas, we're working with millions of points now and the svg approach has become unscalable, so I am looking toward raster solutions and found this repo (which is amazing, by the way). It'd be great to have the ability to splat points with a specified alpha in datamaps -- but looking through the code I'm not really sure where to start. I've tried some post-processing approaches, but can't find a good mapping from color to alpha. For the best so far I've had to resort to single color and mapping greyscale directly to alpha, which leaves large square grey regions around each point:

![screenshot 2014-06-30 17 15 00](https://cloud.githubusercontent.com/assets/10985/3435989/af9b8512-009b-11e4-84bb-1e853cd895cd.png)

Thoughts?

**Comment by e-n-f** [comment]
If you want to change the drawing behavior, the place to look is the out() function in graphics.c, which takes the sum that has accumulated through drawing dots and turns it into RGBA pixel values for the output.

You may be able to get close to what you want just by specifying -t 0 so that it's drawing on a transparent background, not on black. This should also give you fractional transparency on the fringes rather than opaque but medium-brightness pixels.

I'm not sure if you were also asking about changing the rate at which the colors saturate—I can go into more detail about how the brightness settings work if that is confusing.

**Comment by Meekohi** [comment]
Thanks Eric I will investigate that. Already using -t 0. I've done some experimenting with the brightness settings as well and they seem well documented. I'll let you know if I have a pull request or question. Thanks again!

**Comment by e-n-f** [comment]
Thanks. It also just occurs to me that you are drawing on a light background, so you probably also want -w so that colors are building toward black rather than toward white.
