### ISSUE TITLE
Time based colouring

### ISSUE THREAD

**Issue by umaar** [e-n-f/datamaps#16]
Hey @ericfischer - assume that for each data point, I have a percentage for how far into the day it occurred. What could I feed into the `encode` script to have it consider this for colouring? I'd like to end up with something where I can see that data points within a certain geographic area happened early in the day, whereas data points within another area happened later into the day. Ideas are appreciated, thank you!

**Comment by e-n-f** [comment]
Thanks for the question. A percentage takes at least 7 bits of metadata (since 2^7=128 is the next power of two past 100), so you would need to specify that much space when encoding:

```
encode -m7
```

to reserve 7 bits of metadata. You would write the data records themselves as

```
lat,lon 7:number
```

And then when rendering you would use

```
render -C100
```

to give each metadata value from 0 to 99 a color around the color wheel.

**Comment by umaar** [comment]
That's exactly what I wanted to know. Thank you for the quick reply and detailed explanation!
